title: "Oma Sivusto"
description: "Kuvaus sivustosta"
baseurl: "" # Jos sivu ei ole alikansiossa
url: "https://www.jeresoininen.fi" # Korvaa omalla sivusi URL-osoitteella

author:
  name: "Oma Nimi"
  email: "sähköposti@example.com"
  bio: "Lyhyt kuvaus itsestäsi"
  avatar: "/path/to/avatar.jpg" # Lisää avatar tarvittaessa

defaults:
  - scope:
      path: ""
    values:
      layout: "single"

# Teeman asetukset
minimal_mistakes_skin: "default"
