remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-include-cache

title: "Oma Sivusto"
description: "Kuvaus sivustosta"
baseurl: "" # jätä tyhjäksi, jos ei ole alikansioita
url: "https://www.jeresoininen.fi" # korvaa omalla sivustosi URL:llä

author:
  name: "Jere Soininen"
  bio: "Olen kolmannen vuoden opiskelija joka erikoistuu data analytiikkaan päläläälälälä."
